### ISSUE TITLE
Need a sample application

### ISSUE THREAD

**Issue by mat-mcloughlin** [fr1zle/vscode-elixir#47]
Could do with a standard application that contains most of the elixir syntax. Then we can use it to test against

@fr1zle any recommendations?

**Comment by ctrlShiftBryan** [comment]
I'd love to help here. Would a phoenix application make sense? Should it just be another repo on github somewhere or actually in this repo? Would a git submodule make sense? 

If you like the submodule idea we could do the same for the alchemist sever and then just use our own fork in order to stay up to date with changes on from @tonini.

**Comment by mat-mcloughlin** [comment]
tbh anything will do. I was hoping to find something that was already out there but I'm happy with anything. If you want to build something by all means

**Comment by Lokeh** [comment]
It looks like atom-elixir uses this a minimal sample: https://github.com/msaraiva/atom-elixir/blob/master/spec/fixtures/sample.ex
```elixir
top_level_var = "top_level_var"

defmodule Sample do
  import List
  alias Enum, as: MyEnum

  @module_attr false

  def test do
    module_var = [1,2,[3]]
    my_inspect(module_var |> flatten |> MyEnum.count)
  end

  def my_inspect(param1) do
    IO.inspect(param1)
  end

end
```
