### ISSUE TITLE
Better way to manage to alchemist server

### ISSUE THREAD

**Issue by mat-mcloughlin** [fr1zle/vscode-elixir#49]
Ideally I'd like to pull it in as a git submodule to better manage the upgrades. That being said though if alchemist isn't being worked as much anymore it might make sense to fork our own copy of it and pull that instead

@fr1zle thoughts?

**Comment by Korbin73** [comment]
This makes a lot of sense. In elixir 1.4, there are a lot of warnings that are getting logged at compile time. I had to change some code in the extension on my local machine to ignore warnings because it was flagging that the alchemy server was busy. Should I do a pr for this minor fix? Or will you guys be taking on a copy of alchemist and resolving the warnings?

**Comment by fr1zle** [comment]
Alchemist has been / will be replaced by elixir_sense which is submoduled.
