### ISSUE TITLE
Need someone to take over the project

### ISSUE THREAD

**Issue by mat-mcloughlin** [fr1zle/vscode-elixir#54]
Hey guys, 

I started this project over a year ago now as a little investigation into how you could add elixir support to visual studio. Since then the project has gathered a bit of momentum and there are now quite a few people using it. 

However, throughout this time I haven't really looked after the project as I should. I kept promising myself that I would eventually find the time to sort this, which is why I've kept hold of it for so long, but unfortunately that time has never materialised. 

This is partly due to becoming a parent :D

Its due to this that I realistically need some people to take this project off my hands. Although its still in its infancy I don't want to see it die as its currently had **22,000** downloads from the visual studio market place. So if you are interested please get in touch and we can sort something out. 

@fr1zle you obviously get first dibs on this.

**Comment by fr1zle** [comment]
Hey @mat-mcloughlin,

when I decided to build the auto-complete feature in vs-code i basically had the choice between publishing a new plugin or adding to the one you created. Since the open source philosophy always very close to my heart i decided against creating a new plugin and instead contributed to yours.
My contribution obviously changed the project from fairly low maintanence to needing updates with every new release of elixir. But I think it also drove users to our plugin and 22,000 downloads is a great accomplishment on our parts.
I can totally understand you not being able to keep up with the work required anymore, and I would be willing to take it from here. Seeing that we get more and more contributions from the community, I see a great feature for this little plugin :-)

We should get in touch in the next days and sort out the marketplace and github stuff!

**Comment by mat-mcloughlin** [comment]
@fr1zle meet me on gitter now?

**Comment by fr1zle** [comment]
We are currently trying to figure out how to move this extension on the vs code marketplace so that there is no action required by our users:
https://github.com/Microsoft/vscode/issues/21478

**Comment by mat-mcloughlin** [comment]
@fr1zle they've updated it, if you let me know how you wanna proceed

**Comment by fr1zle** [comment]
@mat-mcloughlin check gitter :-)

**Comment by mat-mcloughlin** [comment]
@fr1zle I'm trying to give you publishing rights but I'll be damned if I can find the web page to do so. I've asked the question but if you can find it?

**Comment by fr1zle** [comment]
@mat-mcloughlin only way i can think off is you giving me an access key thingy in VS Team Services... Maybe reopen the ticket in vscode?

**Comment by mat-mcloughlin** [comment]
you think this would be easier :) I don't have the permissions to re-open. I'll keep chasing but in the mean time if you need me to publish I can

**Comment by fr1zle** [comment]
@mat-mcloughlin they answered, did you get around to try their solution yet?

**Comment by mat-mcloughlin** [comment]
I noticed. I'll give it a shot tonight

**Comment by mat-mcloughlin** [comment]
@fr1zle 

"Under Roles you can add additional users and give them publish access. You need to use the login that the user will have for VSTS. They will also need to have created a Personal Access Token for that account with access to all accounts."

Need some details

**Comment by fr1zle** [comment]
@mat-mcloughlin lets talk on gitter

**Comment by fr1zle** [comment]
@mat-mcloughlin I was able to push an update, i guess we can close this issue now?

**Comment by mat-mcloughlin** [comment]
yep that all looks good to me. By all means get in touch if you need me for anything else
